"""Shared UI and native diagnostic translations; only writes language/message resources."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UI = {
    "prefabdeploy.reload.started": ("Reloading prefab data...", "正在重载建筑数据…"),
    "prefabdeploy.reload.busy": ("Prefab data is already reloading", "建筑数据正在重载"),
    "prefabdeploy.reload.failed": ("Prefab data reload failed; check the server log", "建筑数据重载失败，请检查服务器日志"),
    "prefabdeploy.reload.completed": ("Loaded %s buildings (%s unavailable)", "已读取 %s 个建筑（%s 个不可用）"),
    "prefabdeploy.local.open_folder": ("Open blueprint folder", "打开蓝图文件夹"),
    "prefabdeploy.local.formats": ("Supported: .litematic (versions 5–7), structure .nbt\nMinecraft 1.21.1 / DataVersion 3955", "支持：.litematic（格式版本 5–7）、结构 .nbt\nMinecraft 1.21.1 / DataVersion 3955"),
    "prefabdeploy.local.host_only_tooltip": ("\nAvailable only to the singleplayer or LAN world host.", "\n仅单人玩家或局域网主机可用。"),
    "prefabdeploy.local.host_only": ("Local blueprints are available only to the world host", "本地蓝图仅世界主机可用"),
    "prefabdeploy.local.category": ("Local blueprints", "本地蓝图"),
    "prefabdeploy.local.folder_read_failed": ("Unable to read the blueprint folder", "无法读取蓝图文件夹"),
    "prefabdeploy.local.folder_open_failed": ("Unable to open the blueprint folder", "无法打开蓝图文件夹"),
    "prefabdeploy.local.registry_failed": ("Unable to apply blueprint scripts; check the server log", "无法应用蓝图脚本，请检查服务器日志"),
    "creativetab.prefabdeploy": ("Prefab Deploy", "预制建筑"),
    "item.prefabdeploy.deployment_tool": ("Deployment Tool", "建筑部署工具"),
    "block.prefabdeploy.positioning_beacon": ("Positioning Beacon", "位置信标"),
    "key.prefabdeploy.rotate": ("Rotate prefab clockwise", "顺时针旋转建筑"),
    "key.categories.prefabdeploy": ("Prefab Deploy", "预制建筑部署"),
    "prefabdeploy.library": ("Prefab Library", "预制建筑库"),
    "prefabdeploy.search": ("Search buildings…", "搜索建筑…"),
    "prefabdeploy.library_count": ("%s buildings", "%s 个建筑"),
    "prefabdeploy.filtered_count": ("%s / %s buildings", "%s / %s 个建筑"),
    "prefabdeploy.quick": ("Crosshair placement", "准星定位"),
    "prefabdeploy.beacons": ("Three-beacon placement", "三点信标定位"),
    "prefabdeploy.category": ("Category: %s", "分类：%s"),
    "prefabdeploy.locked": ("Locked", "尚未解锁"),
    "prefabdeploy.dimensions": ("X %s × Z %s · Height %s", "X %s × Z %s · 高度 %s"),
    "prefabdeploy.reference": ("Above reference: %s | Below: %s", "参考面以上：%s ｜地下：%s"),
    "prefabdeploy.cost": ("Deployment cost", "部署成本"),
    "prefabdeploy.conditions": ("Requirements: %s", "条件：%s"),
    "prefabdeploy.available": ("Available · server will verify placement", "条件满足 · 最终位置由服务器验证"),
    "prefabdeploy.empty": ("No matching visible buildings.", "没有匹配的可见建筑。"),
    "prefabdeploy.loading_preview": ("Loading preview…", "正在读取预览…"),
    "prefabdeploy.building_preview": ("Preparing geometry: %s blocks", "正在准备模型：%s 个方块"),
    "prefabdeploy.preview_controls": ("Drag to rotate · Scroll to zoom", "拖动旋转 · 滚轮缩放"),
    "prefabdeploy.preview_decode_failed": ("Preview decode failed: %s", "预览解码失败：%s"),
    "prefabdeploy.follow_help": ("R: rotate clockwise | Right-click inside the preview frame to fix | Right-click outside to cancel | Shift+right-click: cancel", "R 顺时针旋转｜对预览外框内右键固定｜外框外右键取消｜Shift+右键取消"),
    "prefabdeploy.fixed_help": ("Right-click inside the preview frame to deploy; retry placement if invalid | Right-click outside to cancel | Shift+right-click: cancel", "对预览外框内右键部署；无效时重新定位｜外框外右键取消｜Shift+右键取消"),
    "prefabdeploy.beacon_help": ("Place A → B → C, then use the tool | Right-click air: floating beacon | Shift+scroll: distance | Tool right-click or Shift+right-click: cancel", "放置 A → B → C 后换回工具｜对空气右键浮空｜Shift+滚轮调距离｜工具右键或 Shift+右键取消"),
    "prefabdeploy.anchor": ("A: %s · Rotation %s°", "A：%s · 旋转 %s°"),
    "prefabdeploy.beacon_metrics": ("%s: distance %s/%s · Height %s/%s · %s", "%s：距离 %s/%s · 高度 %s/%s · %s"),
    "prefabdeploy.position_valid": ("Valid", "有效"),
    "prefabdeploy.position_invalid": ("Invalid", "无效"),
    "prefabdeploy.deploying": ("Deploying… Construction chunks are locked.", "正在部署… 施工区块暂时锁定。"),
    "prefabdeploy.completed": ("Building deployed. Transaction: %s", "建筑部署完成，交易编号：%s"),
    "prefabdeploy.failed": ("Deployment failed: %s", "部署失败：%s"),
    "prefabdeploy.cost.creative": ("Creative mode — free", "创造模式免费"),
    "prefabdeploy.cost.free": ("Free", "免费"),
    "prefabdeploy.cost.material": ("%s × %s", "%s × %s"),
    "prefabdeploy.cost.xp": ("%s XP points", "%s 经验点数"),
    "prefabdeploy.cost.money": ("%s ViScriptShop currency", "%s ViScriptShop 货币"),
    "prefabdeploy.cost.custom": ("Custom cost: %s", "自定义费用：%s"),
    "prefabdeploy.cost.lava": ("%s lava buckets (or %s mB from the bound network)", "%s 桶岩浆（也可用绑定网络中的 %s mB 岩浆支付）"),
    "prefabdeploy.resource.adapter_version": ("Resource adapter requires %s %s", "资源兼容需要 %s %s 版本"),
    "prefabdeploy.resource.unavailable": ("Resource source unavailable: %s", "资源来源不可用：%s"),
    "prefabdeploy.resource.reservation_failed": ("Resource reservation failed: %s", "资源预留失败：%s"),
    "prefabdeploy.resource.missing_lava": ("Missing lava: %s blocks; each needs a lava bucket or 1000 mB from the bound network", "缺少 %s 格岩浆材料；每格需要一桶岩浆或绑定网络中的 1000 mB 岩浆"),
    "prefabdeploy.resource.refund_pending": ("Original resource storage is full; refund is pending", "原资源存储已满，退款等待恢复"),
    "prefabdeploy.resource.recovery_pending": ("Resource recovery is pending; retain the receipt and retry recovery: %s", "资源交易等待恢复；请保留凭据并重试恢复：%s"),
    "prefabdeploy.text.and_separator": ("; ", "；"),
    "prefabdeploy.text.or_separator": (" / ", " / "),
    "prefabdeploy.rule.none": ("None", "无"),
    "prefabdeploy.rule.disabled": ("Unavailable", "不可用"),
    "prefabdeploy.rule.any": ("One of: %s", "满足任一项：%s"),
    "prefabdeploy.rule.not": ("Excluded: %s", "排除：%s"),
    "prefabdeploy.rule.advancement": ("Advancement: %s", "进度：%s"),
    "prefabdeploy.rule.quest": ("FTB Quest: %s", "FTB 任务：%s"),
    "prefabdeploy.rule.dimension": ("Dimension: %s", "维度：%s"),
    "prefabdeploy.rule.flag": ("%s unlock: %s", "%s解锁标记：%s"),
    "prefabdeploy.rule.player": ("player", "玩家"),
    "prefabdeploy.rule.team": ("team", "团队"),
    "prefabdeploy.rule.script": ("Rule: %s", "规则：%s"),
    "prefabdeploy.rule.unknown": ("Unavailable rule", "规则不可用"),
    "prefabdeploy.rule.unavailable_details": ("Condition unavailable: %s", "条件不可用：%s"),
}
ERRORS = [
    ("Resource persistence adapter unavailable", "资源持久化兼容不可用"),
    ("Bound network changed or permission was revoked", "绑定网络已改变或权限已撤销"),
    ("Bound network permission unavailable", "没有绑定网络的访问权限"),
    ("Funding backpack is no longer carried", "用于支付的背包已不在身上"),
    ("Material changed before reservation", "材料在扣取前发生变化"),
    ("Resource receipt file is missing; recovery is pending", "资源凭据文件缺失，交易等待恢复"),
    ("Resource receipt file differs; recovery is pending", "资源凭据文件不一致，交易等待恢复"),
    ("Resource receipt file cannot be read; recovery is pending", "无法读取资源凭据文件，交易等待恢复"),
    ("Original network is unavailable; recovery is pending", "原网络不可用，交易等待恢复"),
    ("Original backpack is unavailable; recovery is pending", "原背包不可用，交易等待恢复"),
    ("Resource result is uncertain; recovery is pending", "资源扣取结果不确定，交易等待核对"),
    ("Resource reservation is incomplete; recovery is pending", "资源预留未完成，交易等待恢复"),
    ("Resource transaction could not be saved", "无法保存资源交易"),
    ("Unable to read blueprint data", "无法读取蓝图数据"),
    ("Too many prefab requests; try again", "操作过于频繁，请稍后再试"),
    ("Construction has started; cancellation is unavailable", "已开始施工，无法取消"),
    ("Checking placement…", "正在验证放置位置…"),
    ("Deployment already active", "已有建筑正在部署"),
    ("A prefab task is already active", "已有预制建筑任务正在执行"),
    ("Unknown prefab", "未知建筑"),
    ("Placement session expired", "定位会话已失效，请重新选择建筑"),
    ("Place all three positioning beacons", "请先放置全部三枚定位信标"),
    ("Placement beyond maximum distance", "放置位置超过最大距离"),
    ("Wait for successful placement validation", "请等待放置验证通过"),
    ("Unknown request", "未知操作请求"),
    ("A library entry is too large; shorten its metadata or material description", "建筑条目过大，请缩短元数据或材料说明"),
    ("Preview too large", "预览数据过大"),
    ("Preview generation failed", "预览生成失败"),
    ("Positioning is already complete", "定位已经完成"),
    ("Placement dimension changed", "定位所在维度已改变"),
    ("Beacons must share the reference height", "信标必须处于同一参考高度"),
    ("B must be exactly %s blocks along one axis", "B 必须沿一条水平轴与 A 相距 %s 格"),
    ("C must mark the perpendicular Z boundary (distance %s)", "C 必须位于垂直的 Z 轴边界（距离 %s 格）"),
    ("A positioning beacon was removed; placement cancelled", "定位信标已被移除，定位已取消"),
    ("Positioning beacon missing; placement cancelled", "定位信标缺失，定位已取消"),
    ("A positioning beacon was removed", "定位信标已被移除"),
    ("Beacon position is not loaded or outside world limits", "信标位置未加载或超出世界范围"),
    ("Floating beacon needs an empty position", "浮空信标需要空的位置"),
    ("Construction area is locked", "施工区域已锁定"),
    ("Spawn protection", "出生点保护区域"),
    ("Server spawn protection", "服务器出生点保护区域"),
    ("Rule denied", "规则不允许部署"),
    ("No alternative condition satisfied", "未满足任何备选条件"),
    ("Excluded by rule", "被规则排除"),
    ("Advancement required: %s", "需要完成进度：%s"),
    ("FTB quest required: %s", "需要完成 FTB 任务：%s"),
    ("Dimension condition not satisfied", "不满足维度条件"),
    ("Unlock flag required: %s", "需要解锁标记：%s"),
    ("Condition unavailable: FTB Quests is required", "条件不可用：需要安装 FTB Quests"),
    ("Condition unavailable: FTB Teams is required", "条件不可用：需要安装 FTB Teams"),
    ("Condition unavailable: missing script rule %s", "条件不可用：缺少脚本规则 %s"),
    ("Condition unavailable: unknown rule %s", "条件不可用：未知规则 %s"),
    ("Condition unavailable: %s", "条件不可用：%s"),
    ("Building is hidden", "建筑不可见"),
    ("Server position limit exceeded", "超过服务器位置数量限制"),
    ("Server blueprint size limit exceeded", "超过服务器蓝图大小限制"),
    ("FTB Teams is required", "需要安装 FTB Teams"),
    ("FTB Quests is required", "需要安装 FTB Quests"),
    ("No FTB team", "未加入 FTB 团队"),
    ("FTB Chunks: no edit permission at %s", "FTB 领地：无权修改位置 %s"),
    ("FTB Chunks permission adapter unavailable: %s", "FTB 领地权限接口不可用：%s"),
    ("ViScriptShop is required", "需要安装 ViScriptShop"),
    ("ViScriptShop currency configuration unavailable", "ViScriptShop 货币配置不可用"),
    ("Replacement currency needs a recoverable CostProvider", "替代货币需要支持恢复的费用适配器"),
    ("ViScriptShop deduction mismatch", "ViScriptShop 扣款结果不一致"),
    ("Cost provider unavailable: %s", "费用提供者不可用：%s"),
    ("Cannot price block automatically: %s; use manual pricing", "无法自动计算方块 %s 的材料，请使用手动定价"),
    ("Explicit cost definition required (use mode: free)", "必须配置费用；免费建筑请使用 free 模式"),
    ("Unknown cost mode", "未知费用模式"),
    ("Unknown cost item: %s", "未知费用物品：%s"),
    ("Item cost must be positive", "物品费用数量必须大于零"),
    ("Negative XP cost", "经验费用不能为负数"),
    ("Currency amount must be nonnegative with at most two decimals", "货币金额必须非负，且最多两位小数"),
    ("Missing recoverable cost provider: %s", "缺少支持恢复的费用提供者：%s"),
    ("Missing material: %s %s/%s", "材料不足：%s，已有 %s，需要 %s"),
    ("Not enough XP points", "经验点数不足"),
    ("Not enough ViScriptShop currency", "ViScriptShop 余额不足"),
    ("ViScriptShop adapter unavailable", "ViScriptShop 接口不可用"),
    ("Currency API returned an unknown payment state", "货币接口返回了未知的付款状态"),
    ("Currency deduction mismatch", "货币扣款结果不一致"),
    ("Cost reservation failed", "费用预留失败"),
    ("Cannot refund committed transaction", "无法退款已结算的交易"),
    ("Currency result is uncertain; audit and reconcile before retrying", "货币状态不确定，请先核对交易再重试"),
    ("Recovery cost provider missing", "缺少恢复交易所需的费用提供者"),
    ("Currency refund mismatch", "货币退款结果不一致"),
    ("Currency refund unavailable or uncertain", "货币退款不可用或状态不确定"),
    ("Cannot settle a missing or refunded cost receipt", "无法结算缺失或已退款的费用凭据"),
    ("Settlement provider missing", "缺少交易结算提供者"),
    ("Player transaction could not be saved", "无法保存玩家交易"),
    ("Affected chunk limit exceeded", "受影响区块数量超过限制"),
    ("Deployment dimension is unavailable", "部署维度不可用"),
    ("Another task has locked these chunks", "其他任务已锁定这些区块"),
    ("Player disconnected", "玩家已断开连接"),
    ("Player disconnected before payment", "玩家在预留费用前断开连接"),
    ("Explore chunk before deployment: %s", "请先探索区块再部署：%s"),
    ("Chunk could not be loaded", "无法加载区块"),
    ("Forbidden entity: %s", "禁止部署实体：%s"),
    ("Entity could not be loaded", "无法加载实体"),
    ("Player entered the construction area", "玩家进入了施工区域"),
    ("Block placement was rejected at %s", "位置 %s 的方块放置被拒绝"),
    ("Entity creation failed", "实体生成失败"),
    ("Entity identity collision", "实体身份冲突"),
    ("Rollback block rejected", "恢复方块时被拒绝"),
    ("Outside world limits: %s", "位置超出世界范围：%s"),
    ("Protected block: %s at %s", "受保护方块：%s，位置：%s"),
    ("Forbidden blueprint content: %s", "蓝图含有禁止部署的内容：%s"),
    ("Original world snapshot exceeds the 128 MiB safety limit", "原世界快照超过 128 MiB 安全限制"),
    ("Recovery journal exceeds its safety limit; no payment was reserved", "恢复记录超过安全限制，未预留费用"),
    ("Unknown fluid tick type", "未知流体 Tick 类型"),
    ("Unknown block tick type", "未知方块 Tick 类型"),
    ("Block entity could not be loaded at %s", "无法加载位置 %s 的方块实体"),
    ("Compressed blueprint too large", "压缩蓝图文件过大"),
    ("Blueprint must use Minecraft 1.21.1 DataVersion 3955; found %s", "蓝图必须使用 Minecraft 1.21.1 数据版本 3955，当前为 %s"),
    ("Blueprint has no affected positions", "蓝图没有可处理的位置"),
    ("Entity/tick limit exceeded", "实体或 Tick 数量超过限制"),
    ("Unknown block entity", "未知方块实体"),
    ("Block entity is incompatible with block at %s", "位置 %s 的方块实体与方块不兼容"),
    ("Tick outside blueprint bounds", "Tick 位置超出蓝图范围"),
    ("Unknown scheduled tick type", "未知计划 Tick 类型"),
    ("Entity hierarchy limit exceeded", "实体层级或数量超过限制"),
    ("Unknown entity: %s", "未知实体：%s"),
    ("Duplicate entity UUID in blueprint", "蓝图中存在重复实体 UUID"),
    ("Invalid entity coordinates", "实体坐标无效"),
    ("Invalid blueprint bounds", "蓝图边界无效"),
    ("Too many positions", "位置数量过多"),
    ("Empty palette", "方块调色板为空"),
    ("Invalid packed index", "打包方块索引无效"),
    ("Truncated block states", "方块状态数据被截断"),
    ("Region exceeds position limit: %s", "区域位置数量超过限制：%s"),
    ("Invalid leash coordinates", "拴绳坐标无效"),
    ("Supported litematic versions: 5..7", "仅支持 Litematic 格式版本 5 至 7"),
    ("No litematic regions", "Litematic 文件没有区域"),
    ("Position limit exceeded", "位置数量超过限制"),
    ("Conflicting overlapping regions at %s", "位置 %s 的重叠区域存在冲突"),
    ("Invalid entity position", "实体位置无效"),
    ("Missing passenger position", "缺少乘客实体位置"),
    ("NBT content nesting exceeds 64 levels", "NBT 嵌套超过 64 层"),
    ("Unknown stored item: %s", "未知库存物品：%s"),
    ("Unknown stored item component: %s", "未知库存物品组件：%s"),
    ("Unknown block: %s", "未知方块：%s"),
    ("Unknown property: %s", "未知方块属性：%s"),
    ("Invalid state value: %s", "方块状态值无效：%s"),
    ("Missing structure size", "结构缺少尺寸"),
    ("Invalid block position", "方块位置无效"),
    ("Position outside structure", "位置超出结构范围"),
    ("Duplicate structure position", "结构中存在重复位置"),
    ("Unsupported journal version", "不支持此恢复记录版本"),
    ("Invalid journal transform", "恢复记录中的坐标变换无效"),
    ("Invalid beacon refund count", "信标返还数量无效"),
    ("Missing source: %s", "缺少蓝图源文件：%s"),
    ("Unsupported format: %s", "不支持的蓝图格式：%s"),
    ("Unsupported blueprint format: %s", "不支持的蓝图格式：%s"),
    ("Ground reference outside blueprint", "地面参考层超出蓝图范围"),
    ("Atomic replacement interrupted", "原子保存被中断"),
    ("Atomic journal replacement is required on this filesystem", "当前文件系统无法原子保存恢复记录"),
    ("Invalid journal size", "恢复记录大小无效"),
    ("Journal checksum mismatch", "恢复记录校验失败"),
]

def write_resources():
    en = {key: values[0] for key, values in UI.items()}
    zh = {key: values[1] for key, values in UI.items()}
    messages = []
    for english, chinese in ERRORS:
        key = "prefabdeploy.error." + re.sub(r"[^a-z0-9]+", "_", english.lower().replace("%s", "arg")).strip("_")
        en[key], zh[key] = english, chinese
        pattern = "^" + "(.*?)".join(re.escape(part) for part in english.split("%s")) + "$"
        messages.append({"key": key, "fallback": english, "pattern": pattern})
    assets = ROOT / "src/main/resources/assets/prefabdeploy"
    (assets / "lang").mkdir(parents=True, exist_ok=True)
    for filename, content in (("lang/en_us.json", en), ("lang/zh_cn.json", zh), ("messages.json", messages)):
        (assets / filename).write_text(json.dumps(content, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

if __name__ == "__main__":
    write_resources()
